// Escreva os comandos SQL para criar estas tabelas no banco de dados.

CREATE TABLE PACIENTE (

    CODIGO INTEGER NOT NULL,
    NOME VARCHAR(256) NOT NULL,
    EMAIL VARCHAR(256),
    CELULAR VARCHAR(120) NOT NULL,
    CONSTRAINT PK_PACIENTE PRIMARY KEY(CODIGO)

)

CREATE TABLE FISIOTERAPEUTA (

    CODIGO INTEGER NOT NULL,
    NOME VARCHAR(256) NOT NULL,
    NUMERO_CONSELHO VARCHAR(120) NOT NULL,
    EMAIL VARCHAR(256),
    CONSTRAINT PK_FISIOTERAPEUTA PRIMARY KEY(CODIGO)

)

CREATE TABLE TIPOATENDIMENTO (

    CODIGO INTEGER NOT NULL,
    DESCRICACAO VARCHAR(100),
    CONSTRAINT PK_ TIPOATENDIMENTO PRIMARY KEY(CODIGO)

)

CREATE TABLE ATENDIMENTO (

    CODIGO INTEGER NOT NULL,
    DATA_ATENDIMENTO DATE NOT NULL,
    HORA TIME NOT NULL,
    TOTAL INT NOT NULL,
    PACIENTE_CODIGO INTEGER NOT NULL,
    FISIO_CODIGO INTEGER NOT NULL,
    TIPOATENDIMENTO _CODIGO INTEGER NOT NULL,
    CONSTRAINT PK_ATENDIMENTO PRIMARY KEY(CODIGO),
    FOREIGN KEY(PACIENTE_CODIGO) REFERENCES PACIENTE(CODIGO) ON
    UPDATE CASCADE,
    FOREIGN KEY(FISIO_CODIGO) REFERENCES FISIOTERAPEUTA(CODIGO) ON
    UPDATE CASCADE,
    FOREIGN KEY(TIPOATENDIMENTO _CODIGO) REFERENCES
    TIPOATENDIMENTO (CODIGO) ON UPDATE CASCADE

)

// Escreva o comando SQL para mostrar os atendimentos(data, hora) com os nomes dos pacientes e fisioterapeutas.

    SELECT ATENDIMENTO.CODIGO, DATA_ATENDIMENTO, HORA,
    PACIENTE.NOME, FISIOTERAPEUTA.NOME
    FROM ATENDIMENTO
    INNER JOIN PACIENTE ON
    ATENDIMENTO.PACIENTE_CODIGO = PACIENTE.CODIGO
    INNER JOIN FISIOTERAPEUTA ON
    ATENDIMENTO.FISIO_CODIGO = FISIOTERAPEUTA.CODIGO

// Escreva o comando SQL para mostrar a quantidade de atendimentos por tipo de atendimento.

    SELECT T.DESCRICACAO, COUNT(*) FROM ATENDIMENTO A JOIN
    TIPOATENDIMENTO T ON T.CODIGO=A.TIPOATENDIMENTO_CODIGO
    GROUP BY T.DESCRICACAO

// Escreva o comando SQL para mostrar o total de atendimentos por tipo de atendimento.

    SELECT T.DESCRICACAO, SUM(A.TOTAL) FROM ATENDIMENTO A JOIN
    TIPOATENDIMENTO T ON T.CODIGO=A.TIPOATENDIMENTO_CODIGO
    GROUP BY T.DESCRICACAO

// Crie uma role chamada “CADASTRO”.

    CREATE ROLE CADASTRO;

// De acesso total a tabelas PACIENTE e FISIOTERAPEUTA para role CADASTRO.

    GRANT ALL ON TABLE PACIENTE TO CADASTRO;
    GRANT ALL ON TABLE FISIOTERAPEUTA TO CADASTRO;

// De acesso apenas de select e update para tabela ATENDIMENTO para a role CADASTRO.

    GRANT SELECT, UPDATE ON TABLE ATENDIMENTO TO ROLE CADASTRO;

// Crie um usuário chamado ANTONIO com a senha ‘master’.

    CREATE USER ANTONIO PASSWORD 'master';

// Associe este usuário ANTONIO a role CADASTRO.

    GRANT CADASTRO TO ANTONIO;





